name: netease_music_request
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  dio: ^3.0.9
  steel_crypt: ^2.0.0
  crypton: ^1.0.8
  dio_cookie_manager: ^1.0.0
  cookie_jar: ^1.0.1

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
